permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: kramdown

kramdown:
  input: GFM

# 作者信息
author: 
  name: charlotteliu
  email: charlotteldh@163.com
  github: http://github.com/charlotteliu

# 站点信息
title: charlotteliu的博客 
description: charlotteliu的博客
url: http://charlotteliu.github.io
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: http://7u2ho6.com1.z0.glb.clouddn.com/gavatar.png
favicon: http://7u2ho6.com1.z0.glb.clouddn.com/favicon.ico

# google analytics 设置


# disqus 设置
disqus:
  shortname: charlotteliu

# 主题设置，自动激活某个标签
active: 技术

# 首页除了最新文章外显示分类
cates: 
  - Python
  - OpenStack

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
  content: 目录

